version: 2.1

vm_settings: &vm_settings
  docker:
    # https://circleci.com/docs/2.0/circleci-images/#nodejs
    - image: circleci/node:latest-browsers
  working_directory: ~/app

install_restore_cache: &install_restore_cache
  name: Restore cached dependencies
  keys:
    - dependencies-{{ checksum "yarn.lock" }}
    # Fall back to using the latest cache if no exact match is found
    - dependencies

install_run: &install_run
  name: Install dependencies with Yarn, purely from the lockfile
  command: yarn install --frozen-lockfile

install_save_cache: &install_save_cache
  name: Cache installed dependencies
  paths:
    - ~/.cache
  key: dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Run tests
          # Install libgconf, needed by Cypress' Electron, then run tests
          command: sudo apt-get install libgconf-2-4 && yarn test:ci

      # Store test artifacts
      - store_artifacts:
          path: tests/unit/coverage
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: tests/e2e/screenshots

  build:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Build for production
          command: yarn build:ci

      # Store build artifacts
      - store_artifacts:
          path: dist

  deploy:
    <<: *vm_settings
    steps:
      - checkout
      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache
      # Build the app for production
      - run: yarn build
      - add_ssh_keys:
          fingerprints:
            - 'fa:96:61:8d:fc:55:df:5f:d4:42:5a:ce:0b:78:f1:a0'
      - run:
          name: Deploy Over SSH
          command: |
            sudo apt install rsync
            rsync -zarvh -e "ssh -o StrictHostKeyChecking=no" dist/ alexandre_combemorel_gmail_com@35.189.53.139:dev/

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - build
      - deploy:
          # Only deploy if tests pass
          requires:
            - test
          # Only deploy the master branch
          filters:
            branches:
              only: master
