apiVersion: v1
kind: Service
metadata:
  name: gke-test-service
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: gke-test
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gke-test
spec:
  minReadySeconds: 5
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/IMAGE:TAG
          name: gke-test
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
